#!/usr/bin/env python3

class GameConstants:
    """Extract all magic numbers from existing codebase"""

    # COLLISION DETECTION
    PLAYER_COLLISION_RADIUS = 25
    ENEMY_COLLISION_RADIUS = 15
    SHOT_COLLISION_RADIUS = 15
    BOMB_PROXIMITY_FUSE_RADIUS = 20

    # WEAPON COOLDOWNS (seconds)
    BREACH_BOMB_COOLDOWN = 4.0
    CANNON_COOLDOWN = 0.20
    MINI_BOMB_COOLDOWN = 2.0
    WEAK_PULSE_COOLDOWN = 1.5
    TINY_ROCKET_COOLDOWN = 1.0
    SMOKE_BOMB_COOLDOWN = 5.0
    FLICKER_SHOT_COOLDOWN = 1.5
    OVERCHARGE_CANNON_COOLDOWN = 15.0

    # WEAPON SPAWN OFFSETS
    WEAPON_SPAWN_OFFSET_Y = -15
    FLOATING_TEXT_OFFSET_Y = -20

    # PROJECTILE SPEEDS
    ENEMY_SHOT_VELOCITY = 150
    HOMING_DART_VELOCITY = 250

    # WEAPON SPREAD ANGLES (radians)
    BREACH_BOMB_SPREAD_ANGLE = 3.14159 / 12  # math.pi / 12
    CANNON_SPREAD_ANGLE = 3.14159 / 24       # math.pi / 24
    WEAK_PULSE_CONE_ANGLE = 3.14159 / 6      # math.pi / 6

    # WAVE SCALING FACTORS
    ENEMY_HP_SCALING = 1.05          # per wave
    ENEMY_SPEED_SCALING = 1.03       # per wave
    ENEMY_DAMAGE_SCALING = 1.05      # per wave
    ENEMY_SPEED_MULTIPLIER = 1.1

    # ENEMY MOVEMENT LIMITS
    ENEMY_MAX_VX = 200
    ENEMY_MIN_VX = -200
    ENEMY_MAX_VY = 100
    ENEMY_MIN_VY = 0

    # PLAYER STATS
    PLAYER_BASE_HP = 15
    PLAYER_BASE_SHIELD = 15
    PLAYER_BASE_SPEED = 225
    PLAYER_SPEED_MULTIPLIER = 1.1
    PLAYER_ACCEL = 500
    PLAYER_FRICTION = 0.3
    PLAYER_CANNON_DMG = 3.75
    PLAYER_REGEN = 0.5
    PLAYER_RANGE = 100
    PLAYER_MASS = 1000
    PLAYER_RADIUS = 15

    # ENEMY STATS
    BASE_ENEMY_HP = 10
    BASE_ENEMY_SPEED = 50
    BASE_ENEMY_ACCEL = 50
    BASE_ENEMY_FRICTION = 3.0
    BASE_ENEMY_DAMAGE = 5
    ENEMY_RADIUS = 10

    # SCREEN BOUNDARIES AND OFFSETS
    SPAWN_OFFSET = 50               # Enemy spawn distance from screen edge
    BOUNDARY_BUFFER = 50            # Distance beyond screen before cleanup
    ENEMY_SPAWN_Y = -50
    ENEMY_GROUND_Y_OFFSET = 50      # Distance from bottom of screen

    # EFFECT DURATIONS
    EXPLOSION_DURATION = 0.5
    LARGE_EXPLOSION_DURATION = 0.7
    FLOATING_TEXT_DURATION = 1.5
    SMOKE_EFFECT_DURATION = 3.0
    AREA_DENIAL_DURATION = 5.0

    # DROP SYSTEM
    DROP_CHANCE = 0.3
    KERR_SCRAP_MIN = 1
    KERR_SCRAP_MAX = 5

    # EXPERIENCE AND PROGRESSION
    BASE_EXP_REQUIREMENT = 100
    EXP_SCALING = 1.1
    EXP_PER_KILL = 10
    EXP_WAVE_BONUS = 2
    PERK_COST = 10

    # PERK EFFECT VALUES
    FIRE_SHOT_DAMAGE_MULT = 1.3
    BOMB_SHOT_DAMAGE_MULT = 1.3
    BOMB_SHOT_PENETRATION = 0.2
    BLITZ_MODE_SPEED_MULT = 1.2
    DEFENSE_UP_MULT = 1.5
    DEFENSE_UP_DAMAGE_REDUCTION = 0.35
    DAMAGE_REDUCING_REDUCTION = 0.25
    EVASION_CHANCE = 0.35
    CONCENTRATION_DAMAGE_MULT = 1.35

    # BOMB EFFECT MODIFIERS
    COOLDOWN_REDUCTION_15 = 0.85    # 15% cooldown reduction
    COOLDOWN_REDUCTION_25 = 0.75    # 25% cooldown reduction
    AREA_BONUS_10 = 1.1             # +10% area
    AREA_BONUS_25 = 1.25            # +25% area
    AREA_BONUS_30 = 1.3             # +30% area

    # SPECIAL WEAPON PARAMETERS
    ORBITAL_STRIKE_RADIUS = 150
    ORBITAL_STRIKE_DAMAGE = 100
    CLUSTER_BOMB_COUNT = 5          # -2 to +2 range
    CLUSTER_BOMB_SPREAD = 40
    MINI_BOMB_COUNT = 3             # -1 to +1 range
    MINI_BOMB_SPREAD = 50
    MINI_BOMB_VELOCITY = 150
    MINI_BOMB_DAMAGE = 3
    WEAK_PULSE_DAMAGE = 2
    TINY_ROCKET_DAMAGE = 5
    FLICKER_SHOT_DAMAGE = 3
    CLUSTER_BOMB_DAMAGE = 6
    HOMING_DART_DAMAGE = 8

    # ENEMY BEHAVIOR TIMING
    ENEMY_PATTERN_CHANGE_MIN = 2.0
    ENEMY_PATTERN_CHANGE_MAX = 5.0
    ENEMY_SHOOTING_CHANCE = 0.005   # per frame
    ENEMY_CRIT_CHANCE = 0.1
    PLAYER_CRIT_CHANCE = 0.1

    # WAVE MANAGEMENT
    WAVE_CLEAR_DELAY = 5.0
    ENEMIES_PER_WAVE_MULT = 2
    ENEMY_SPAWN_SPREAD = 20         # random offset range
    ENEMY_SPAWN_INTERVAL_BASE = 50  # base spawn spacing

    # UI POSITIONING
    UI_MARGIN = 10
    HP_BAR_WIDTH = 200
    HP_BAR_HEIGHT = 20
    SHIELD_BAR_Y_OFFSET = 30
    TEXT_LINE_HEIGHT = 20
    INVENTORY_VISIBLE_ITEMS = 6
    MENU_ITEM_SPACING = 40
    MENU_START_Y_OFFSET = 100

    # MOVEMENT PATTERNS
    ZIGZAG_FREQUENCY = 2            # sin(time * 2)
    ZIGZAG_AMPLITUDE = 0.2
    STRAIGHT_PATTERN_MULT = 1.0
    CIRCLE_PATTERN_MULT = 0.2
    CIRCLE_ROTATION_SPEED = 0.2

    # PHYSICS CONSTANTS
    EXPLOSIVE_JOULES_PER_KG = 4184000

    # IMPACT DAMAGE CALCULATION
    KINETIC_FACTOR = 0.005
    EXPLOSION_OFFSET_FACTOR = 0.1
    MAX_EXPLOSION_OFFSET = 50
    HIGH_SPEED_THRESHOLD = 100
